import type { PrebuiltTemplate } from "./prebuilt-templates";

/**
 * HARVESTED prebuilt sections (D-278, 2026-06-12) — the best bands rescued from the
 * first generation of built/imported sites (ABC SalesMaster import + Stitch Ottawa
 * demos) before Ali's clean-slate deletion. Images live in the SYSTEM media library
 * (tag "prebuilt"); internal links are genericized to "#". Generated by
 * .stitch-out/harvest-prebuilts.ts — regenerate, don't hand-edit section JSON.
 */
export const HARVESTED_PREBUILTS: PrebuiltTemplate[] = [
  {
    "id": "hv-saas-header",
    "name": "SaaS header — dropdown nav",
    "category": "Headers",
    "icon": "🧭",
    "blurb": "Logo + dropdown menus + CTA, white bar.",
    "sections": [
      {
        "type": "row",
        "_name": "Header",
        "_style": {
          "bg": "#ffffff"
        },
        "columns": 3,
        "children": [
          [
            {
              "text": "Product",
              "type": "heading",
              "align": "center",
              "color": "#3f4554",
              "level": "h3",
              "fontSize": 14
            }
          ],
          [
            {
              "type": "menu",
              "color": "#3f4554",
              "items": [
                {
                  "href": "#",
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "label": "Platform",
                  "children": [
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Platform Overview"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "CRM & Pipelines"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Websites & Funnels"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "AI Builder"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Automations & Workflows"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Consumer Portal"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Marketplace"
                    }
                  ]
                },
                {
                  "href": "#",
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "label": "Solutions",
                  "children": [
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Real Estate"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Mortgage / Finance"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Legal"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Insurance"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Coaching & Consulting"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Agencies"
                    }
                  ]
                },
                {
                  "href": "#",
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "label": "Pricing"
                },
                {
                  "href": "#",
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "label": "Company",
                  "children": [
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "About"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Careers"
                    },
                    {
                      "href": "#",
                      "link": {
                        "url": "#",
                        "href": "#",
                        "kind": "url"
                      },
                      "label": "Partners"
                    }
                  ]
                }
              ],
              "orientation": "horizontal"
            }
          ],
          [
            {
              "href": "#",
              "type": "button",
              "label": "Start Free Trial",
              "radius": 10,
              "bgColor": "#0950c3",
              "variant": "solid",
              "textColor": "#ffffff"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-saas-hero",
    "name": "SaaS hero — split",
    "category": "Hero",
    "icon": "🚀",
    "blurb": "Bold headline, sub, dual CTAs beside product copy.",
    "sections": [
      {
        "gap": 16,
        "type": "row",
        "_name": "Cards",
        "columns": 2,
        "children": [
          [
            {
              "text": "AIBizConnect OS",
              "type": "text",
              "color": "#0950c3",
              "_style": {
                "bg": "#e6eef9",
                "pb": 4,
                "pl": 12,
                "pr": 12,
                "pt": 4,
                "radius": 9999
              },
              "fontSize": 12
            },
            {
              "text": "All‑in‑One AI OS for Professional Services",
              "type": "heading",
              "color": "#0f1729",
              "level": "h1",
              "fontSize": 72
            },
            {
              "text": "Run your entire business—CRM, websites, automations, AI, and client portals—from one platform built for service pros.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 20
            },
            {
              "gap": 12,
              "type": "row",
              "_name": "Buttons",
              "columns": 2,
              "children": [
                [
                  {
                    "href": "#",
                    "type": "button",
                    "label": "Start 14‑Day Free Trial",
                    "radius": 12,
                    "bgColor": "#0950c3",
                    "variant": "solid",
                    "textColor": "#ffffff"
                  }
                ],
                [
                  {
                    "href": "#",
                    "type": "button",
                    "label": "Watch Demo",
                    "radius": 12,
                    "bgColor": "#ffffff",
                    "variant": "solid",
                    "textColor": "#0f1729"
                  }
                ]
              ],
              "contentWidth": "boxed"
            },
            {
              "text": "No credit card required Full access Cancel anytime",
              "type": "text",
              "color": "#65758b",
              "fontSize": 14
            }
          ],
          [
            {
              "url": "https://media.aibizconnect.app/00000000-0000-0000-0000-000000000000/uploads/imported/6a0bf540ffe3bed0451cb6fb302a89af.jpg",
              "type": "image"
            },
            {
              "text": "AI Concierge",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "3 new leads qualified",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 14
            },
            {
              "text": "This week",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "+47% pipeline",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 24
            }
          ]
        ],
        "colStyles": [
          {},
          {}
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-audience-cards",
    "name": "Audience cards",
    "category": "About & Services",
    "icon": "👥",
    "blurb": "\"Who it's for\" persona card grid.",
    "sections": [
      {
        "type": "row",
        "_name": "Who it's for",
        "_style": {
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Who it's for",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "Built for service professionals",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "text": "Industry templates, workflows, and AI tuned for the way you actually work.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 18
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 7,
              "children": [
                [
                  {
                    "text": "Real Estate",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "MLS, IDX, listings & buyer kits.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Mortgage",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Pre‑qual flows & loan pipelines.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Insurance",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Quote intake & renewal automations.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Legal",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Intake, conflicts, matter pipelines.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Advisors",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Client portals & compliance‑ready content.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Coaches",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Programs, bookings, & nurture.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ],
                [
                  {
                    "text": "Agencies",
                    "type": "heading",
                    "align": "center",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 14
                  },
                  {
                    "text": "Multi‑brand, multi‑client management.",
                    "type": "text",
                    "align": "center",
                    "color": "#65758b",
                    "fontSize": 12
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 20,
                  "pl": 20,
                  "pr": 20,
                  "pt": 20,
                  "align": "center",
                  "radius": 12
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-why-band",
    "name": "Why-us feature band",
    "category": "About & Services",
    "icon": "✨",
    "blurb": "Tinted band with three reason cards.",
    "sections": [
      {
        "type": "row",
        "_name": "Why AIBizConnect",
        "_style": {
          "bg": "#fbfcfd",
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Why AIBizConnect",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "The OS for modern service businesses",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 4,
              "children": [
                [
                  {
                    "text": "Run your business in one OS",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "CRM, websites, automations, AI, billing, portals — one login, one source of truth.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "AI that actually does work",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Built‑in assistants score leads, write content, follow up, and route conversations.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Launch fast, scale faster",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Industry templates and ready‑to‑use workflows get you live in hours, not months.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Built for teams & agencies",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Roles, brands, regions, and white‑label deployment baked into every tier.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-testimonial-wall",
    "name": "Testimonial wall",
    "category": "Social Proof",
    "icon": "💬",
    "blurb": "Quote cards with names, star ratings.",
    "sections": [
      {
        "type": "row",
        "_name": "Loved by pros",
        "_style": {
          "bg": "#fbfcfd",
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Loved by pros",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "Trusted across industries",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "text": "\"We replaced 6 tools with AIBizConnect. Onboarding new agents takes a day, not a month.\"",
              "type": "text",
              "color": "#272e3e",
              "fontSize": 16
            },
            {
              "text": "Mara L.",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 14
            },
            {
              "text": "Broker, Realty Group",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "\"The AI brain literally books meetings overnight. It's like a junior SDR that never sleeps.\"",
              "type": "text",
              "color": "#272e3e",
              "fontSize": 16
            },
            {
              "text": "David K.",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 14
            },
            {
              "text": "Mortgage Advisor",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "\"Client portals + automations turned our practice into a polished, modern brand.\"",
              "type": "text",
              "color": "#272e3e",
              "fontSize": 16
            },
            {
              "text": "Sara M.",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 14
            },
            {
              "text": "Insurance Agency Owner",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "Realty Group",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            },
            {
              "text": "PrimeMortgage",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            },
            {
              "text": "SafeGuard Ins.",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            },
            {
              "text": "Hartwell Legal",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            },
            {
              "text": "Capstone Advisors",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            },
            {
              "text": "GrowthLab",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 18
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-steps-watermark",
    "name": "3 steps — watermark numerals",
    "category": "Content",
    "icon": "🪜",
    "blurb": "Process steps with giant faint 01/02/03.",
    "sections": [
      {
        "type": "row",
        "_name": "How it works",
        "_style": {
          "bg": "#fbfcfd",
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "How it works",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "Live in 3 steps",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 3,
              "children": [
                [
                  {
                    "text": "01",
                    "type": "heading",
                    "color": "#e6eef9",
                    "level": "h3",
                    "fontSize": 72
                  },
                  {
                    "text": "STEP 01",
                    "type": "heading",
                    "color": "#0950c3",
                    "level": "h3",
                    "fontSize": 12
                  },
                  {
                    "text": "Start your trial",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 20
                  },
                  {
                    "text": "No credit card. Pick your industry and we'll set things up for you.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "02",
                    "type": "heading",
                    "color": "#e6eef9",
                    "level": "h3",
                    "fontSize": 72
                  },
                  {
                    "text": "STEP 02",
                    "type": "heading",
                    "color": "#0950c3",
                    "level": "h3",
                    "fontSize": 12
                  },
                  {
                    "text": "Launch your first site & pipeline",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 20
                  },
                  {
                    "text": "Use industry templates for websites, funnels, and CRM pipelines.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "03",
                    "type": "heading",
                    "color": "#e6eef9",
                    "level": "h3",
                    "fontSize": 72
                  },
                  {
                    "text": "STEP 03",
                    "type": "heading",
                    "color": "#0950c3",
                    "level": "h3",
                    "fontSize": 12
                  },
                  {
                    "text": "Turn on AI automations",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 20
                  },
                  {
                    "text": "Switch on AI scoring, nudges, and follow‑ups. Watch your pipeline grow.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 28,
                  "pl": 28,
                  "pr": 28,
                  "pt": 28,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 28,
                  "pl": 28,
                  "pr": 28,
                  "pt": 28,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 28,
                  "pl": 28,
                  "pr": 28,
                  "pt": 28,
                  "radius": 12
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-gradient-cta",
    "name": "Gradient CTA band",
    "category": "Conversion",
    "icon": "🌈",
    "blurb": "Full-width blue→cyan gradient call-to-action.",
    "sections": [
      {
        "type": "row",
        "_name": "Ready to run your business in one OS?",
        "_style": {
          "bg": "linear-gradient(to right bottom, rgb(9, 80, 195), rgb(9, 80, 195), rgb(7, 182, 213))",
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Ready to run your business in one OS?",
              "type": "heading",
              "align": "center",
              "color": "#ffffff",
              "level": "h2",
              "fontSize": 48
            },
            {
              "text": "Start your 14‑day free trial. No credit card required.",
              "type": "text",
              "align": "center",
              "color": "#ffffff",
              "fontSize": 18
            },
            {
              "href": "#",
              "type": "button",
              "label": "Start Free Trial",
              "radius": 12,
              "bgColor": "#e1e7ef",
              "variant": "solid",
              "textColor": "#0f1729"
            },
            {
              "text": "View Pricing",
              "type": "text",
              "align": "center",
              "color": "#ffffff",
              "fontSize": 14
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-footer-4col",
    "name": "4-column footer + legal bar",
    "category": "Footers",
    "icon": "🦶",
    "blurb": "Tagline + 3 link columns, © and legal links.",
    "sections": [
      {
        "type": "row",
        "_name": "Section",
        "_style": {
          "bg": "#fbfcfd",
          "mt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 4,
              "children": [
                [
                  {
                    "text": "The all‑in‑one AI OS for professional services. Run your entire business from one platform.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Product",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h4",
                    "fontSize": 14
                  },
                  {
                    "type": "bullet-list",
                    "color": "#65758b",
                    "items": [
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Platform Overview"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "CRM & Pipelines"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Websites & Funnels"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "AI Builder"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Automations & Workflows"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Consumer Portal"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Marketplace"
                      }
                    ],
                    "fontSize": 14,
                    "textColor": "#65758b",
                    "bulletStyle": "none"
                  }
                ],
                [
                  {
                    "text": "Solutions",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h4",
                    "fontSize": 14
                  },
                  {
                    "type": "bullet-list",
                    "color": "#65758b",
                    "items": [
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Real Estate"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Mortgage / Finance"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Insurance"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Legal"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Coaching & Consulting"
                      }
                    ],
                    "fontSize": 14,
                    "textColor": "#65758b",
                    "bulletStyle": "none"
                  }
                ],
                [
                  {
                    "text": "Company",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h4",
                    "fontSize": 14
                  },
                  {
                    "type": "bullet-list",
                    "color": "#65758b",
                    "items": [
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "About"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Partners"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Careers"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Blog"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Guides"
                      },
                      {
                        "link": {
                          "url": "#",
                          "href": "#",
                          "kind": "url"
                        },
                        "text": "Webinars"
                      }
                    ],
                    "fontSize": 14,
                    "textColor": "#65758b",
                    "bulletStyle": "none"
                  }
                ]
              ],
              "colStyles": [
                {},
                {},
                {},
                {}
              ],
              "contentWidth": "boxed"
            },
            {
              "text": "© 2026 AIBizConnect. All rights reserved.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "type": "bullet-list",
              "color": "#65758b",
              "items": [
                {
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "text": "Privacy"
                },
                {
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "text": "Terms"
                },
                {
                  "link": {
                    "url": "#",
                    "href": "#",
                    "kind": "url"
                  },
                  "text": "Security"
                }
              ],
              "fontSize": 12,
              "textColor": "#65758b",
              "bulletStyle": "none"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-pricing-badge",
    "name": "Pricing cards with badge",
    "category": "Conversion",
    "icon": "💳",
    "blurb": "Three plans, highlighted \"Most Popular\".",
    "sections": [
      {
        "gap": 16,
        "type": "row",
        "_name": "Cards",
        "_style": {
          "bg": "#ffffff",
          "pb": 40
        },
        "columns": 5,
        "children": [
          [
            {
              "text": "Starter",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 20
            },
            {
              "text": "For solos getting started.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "$39",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 36
            },
            {
              "text": "/mo",
              "type": "text",
              "color": "#65758b",
              "fontSize": 14
            },
            {
              "href": "#",
              "type": "button",
              "label": "Start Trial",
              "radius": 10,
              "bgColor": "#ffffff",
              "variant": "solid",
              "textColor": "#0f1729"
            },
            {
              "type": "bullet-list",
              "color": "#0f1729",
              "items": [
                {
                  "text": "1 website"
                },
                {
                  "text": "Basic CRM"
                },
                {
                  "text": "Basic automations"
                },
                {
                  "text": "100 AI credits"
                },
                {
                  "text": "Limited email & social"
                },
                {
                  "text": "1 user"
                }
              ],
              "fontSize": 14,
              "textColor": "#0f1729",
              "bulletStyle": "check"
            }
          ],
          [
            {
              "text": "Most Popular",
              "type": "heading",
              "color": "#ffffff",
              "level": "h3",
              "_style": {
                "bg": "#0950c3",
                "pb": 4,
                "pl": 12,
                "pr": 12,
                "pt": 4,
                "radius": 9999
              },
              "fontSize": 12
            },
            {
              "text": "Pro",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 20
            },
            {
              "text": "For growing pros and small teams.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "$89",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 36
            },
            {
              "text": "/mo",
              "type": "text",
              "color": "#65758b",
              "fontSize": 14
            },
            {
              "href": "#",
              "type": "button",
              "label": "Start Trial",
              "radius": 10,
              "bgColor": "#0950c3",
              "variant": "solid",
              "textColor": "#ffffff"
            },
            {
              "type": "bullet-list",
              "color": "#0f1729",
              "items": [
                {
                  "text": "Everything in Starter"
                },
                {
                  "text": "Unlimited websites"
                },
                {
                  "text": "Full CRM"
                },
                {
                  "text": "Full automations"
                },
                {
                  "text": "1,000 AI credits"
                },
                {
                  "text": "Email campaigns"
                },
                {
                  "text": "Social scheduler"
                },
                {
                  "text": "All integrations"
                },
                {
                  "text": "3 users"
                }
              ],
              "fontSize": 14,
              "textColor": "#0f1729",
              "bulletStyle": "check"
            }
          ],
          [
            {
              "text": "Studio",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 20
            },
            {
              "text": "For ambitious teams ready to scale.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "$149",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 36
            },
            {
              "text": "/mo",
              "type": "text",
              "color": "#65758b",
              "fontSize": 14
            },
            {
              "href": "#",
              "type": "button",
              "label": "Start Trial",
              "radius": 10,
              "bgColor": "#ffffff",
              "variant": "solid",
              "textColor": "#0f1729"
            },
            {
              "type": "bullet-list",
              "color": "#0f1729",
              "items": [
                {
                  "text": "Everything in Pro"
                },
                {
                  "text": "10 users"
                },
                {
                  "text": "Funnels"
                },
                {
                  "text": "Advanced automations"
                },
                {
                  "text": "Client portals"
                },
                {
                  "text": "Consumer portal"
                },
                {
                  "text": "AI Consumer Brain"
                },
                {
                  "text": "Priority support"
                }
              ],
              "fontSize": 14,
              "textColor": "#0f1729",
              "bulletStyle": "check"
            }
          ],
          [
            {
              "text": "Agency",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 20
            },
            {
              "text": "Multi‑brand, multi‑client.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "$299",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 36
            },
            {
              "text": "/mo",
              "type": "text",
              "color": "#65758b",
              "fontSize": 14
            },
            {
              "href": "#",
              "type": "button",
              "label": "Start Trial",
              "radius": 10,
              "bgColor": "#ffffff",
              "variant": "solid",
              "textColor": "#0f1729"
            },
            {
              "type": "bullet-list",
              "color": "#0f1729",
              "items": [
                {
                  "text": "Everything in Studio"
                },
                {
                  "text": "5 brands"
                },
                {
                  "text": "5 regions"
                },
                {
                  "text": "20 users"
                },
                {
                  "text": "Unlimited client accounts"
                },
                {
                  "text": "Full white‑label"
                },
                {
                  "text": "Marketplace publishing"
                },
                {
                  "text": "API access"
                }
              ],
              "fontSize": 14,
              "textColor": "#0f1729",
              "bulletStyle": "check"
            }
          ],
          [
            {
              "text": "Enterprise",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 20
            },
            {
              "text": "Tailored for large orgs.",
              "type": "text",
              "color": "#65758b",
              "fontSize": 12
            },
            {
              "text": "Custom",
              "type": "heading",
              "color": "#0f1729",
              "level": "h3",
              "fontSize": 36
            },
            {
              "href": "#",
              "type": "button",
              "label": "Contact Sales",
              "radius": 10,
              "bgColor": "#ffffff",
              "variant": "solid",
              "textColor": "#0f1729"
            },
            {
              "type": "bullet-list",
              "color": "#0f1729",
              "items": [
                {
                  "text": "Everything in Agency"
                },
                {
                  "text": "Unlimited brands & regions"
                },
                {
                  "text": "Unlimited users"
                },
                {
                  "text": "Custom AI models"
                },
                {
                  "text": "SSO"
                },
                {
                  "text": "Compliance"
                },
                {
                  "text": "Dedicated success team"
                }
              ],
              "fontSize": 14,
              "textColor": "#0f1729",
              "bulletStyle": "check"
            }
          ]
        ],
        "colStyles": [
          {
            "bg": "#ffffff",
            "pb": 24,
            "pl": 24,
            "pr": 24,
            "pt": 24,
            "radius": 12
          },
          {
            "bg": "#ffffff",
            "pb": 24,
            "pl": 24,
            "pr": 24,
            "pt": 24,
            "radius": 12
          },
          {
            "bg": "#ffffff",
            "pb": 24,
            "pl": 24,
            "pr": 24,
            "pt": 24,
            "radius": 12
          },
          {
            "bg": "#ffffff",
            "pb": 24,
            "pl": 24,
            "pr": 24,
            "pt": 24,
            "radius": 12
          },
          {
            "bg": "#ffffff",
            "pb": 24,
            "pl": 24,
            "pr": 24,
            "pt": 24,
            "radius": 12
          }
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-checklist-band",
    "name": "What-you-get checklist",
    "category": "Content",
    "icon": "✅",
    "blurb": "Benefit checklist band from the solutions pages.",
    "sections": [
      {
        "type": "row",
        "_name": "What you get",
        "_style": {
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "What you get",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "Everything Real Estate pros need to grow",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 5,
              "children": [
                [
                  {
                    "text": "IDX/VOW website with listing pages",
                    "type": "text",
                    "color": "#272e3e",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Buyer and seller pipelines",
                    "type": "text",
                    "color": "#272e3e",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Buyer kit, listing kit, and CMA tools",
                    "type": "text",
                    "color": "#272e3e",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Drip campaigns by lead source",
                    "type": "text",
                    "color": "#272e3e",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Client portal with saved listings and tours",
                    "type": "text",
                    "color": "#272e3e",
                    "fontSize": 16
                  }
                ]
              ],
              "colStyles": [
                {},
                {
                  "mt": 12
                },
                {
                  "mt": 12
                },
                {
                  "mt": 12
                },
                {
                  "mt": 12
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-capabilities-grid",
    "name": "Capabilities grid",
    "category": "Content",
    "icon": "🧩",
    "blurb": "Feature capability cards (product page).",
    "sections": [
      {
        "type": "row",
        "_name": "Capabilities",
        "_style": {
          "bg": "#fbfcfd",
          "pb": 40,
          "pt": 40
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Capabilities",
              "type": "heading",
              "color": "#0950c3",
              "level": "h3",
              "fontSize": 12
            },
            {
              "text": "Everything you need, built in",
              "type": "heading",
              "color": "#0f1729",
              "level": "h2",
              "fontSize": 36
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 3,
              "children": [
                [
                  {
                    "text": "Smart pipelines",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Custom stages, drag‑and‑drop deals, automation rules per stage.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "360° contact view",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Notes, tasks, calls, emails, files — all in one timeline.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Tasks & follow‑ups",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Auto‑created tasks, queues, and team assignments.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                }
              ],
              "contentWidth": "boxed"
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 3,
              "children": [
                [
                  {
                    "text": "Custom fields & tags",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Model your business with no developer required.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Reporting",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Pipeline velocity, conversion, activity, and rep performance.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "Role‑based access",
                    "type": "heading",
                    "color": "#0f1729",
                    "level": "h3",
                    "fontSize": 18
                  },
                  {
                    "text": "Tight RLS protects every contact by owner.",
                    "type": "text",
                    "color": "#65758b",
                    "fontSize": 14
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                },
                {
                  "bg": "#ffffff",
                  "pb": 24,
                  "pl": 24,
                  "pr": 24,
                  "pt": 24,
                  "radius": 12
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-success-stories",
    "name": "Client success stories",
    "category": "Social Proof",
    "icon": "⭐",
    "blurb": "Navy testimonial trio (Stitch design).",
    "sections": [
      {
        "type": "row",
        "_name": "Client Success Stories",
        "_style": {
          "bg": "#0b1e89",
          "pb": 40,
          "pl": 40,
          "pr": 40,
          "pt": 40,
          "align": "center",
          "bgBlur": true,
          "bgFade": "heavy",
          "radius": 0,
          "shadow": "none",
          "bgImage": "https://media.aibizconnect.app/00000000-0000-0000-0000-000000000000/uploads/imported/06511e76fe425185af3dffbb2bc7757f.png",
          "marginY": 5,
          "paddingX": 20,
          "paddingY": 20,
          "fullWidth": "fluid",
          "bgImageMode": "full-center-parallax",
          "borderColor": "var(--abc-color-border)",
          "borderStyle": "none",
          "borderWidth": 1,
          "bgBlurIntensity": 30
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "Client Success Stories",
              "type": "heading",
              "align": "center",
              "color": "#001e40",
              "level": "h2",
              "fontSize": 32
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 3,
              "children": [
                [
                  {
                    "text": "★★★★★",
                    "type": "text",
                    "color": "#feae2c",
                    "fontSize": 16
                  },
                  {
                    "text": "\"Marc made our first home purchase in Kanata seamless. He explained everything clearly and got us a rate much better than our bank.\"",
                    "type": "text",
                    "color": "#0d1c2f",
                    "fontSize": 16
                  },
                  {
                    "text": "— Sarah & Dave R.",
                    "type": "heading",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "★★★★★",
                    "type": "text",
                    "color": "#feae2c",
                    "fontSize": 16
                  },
                  {
                    "text": "\"Refinancing for renovations felt overwhelming until we spoke to Marc. He found us the equity we needed with minimal hassle.\"",
                    "type": "text",
                    "color": "#0d1c2f",
                    "fontSize": 16
                  },
                  {
                    "text": "— James T.",
                    "type": "heading",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 14
                  }
                ],
                [
                  {
                    "text": "★★★★★",
                    "type": "text",
                    "color": "#feae2c",
                    "fontSize": 16
                  },
                  {
                    "text": "\"As an investor, speed is crucial. Marc delivers every single time with competitive rates and professional advice.\"",
                    "type": "text",
                    "color": "#0d1c2f",
                    "fontSize": 16
                  },
                  {
                    "text": "— Maria P.",
                    "type": "heading",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 14
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "pb": 32,
                  "pl": 32,
                  "pr": 32,
                  "pt": 32,
                  "radius": 16
                },
                {
                  "bg": "#ffffff",
                  "pb": 32,
                  "pl": 32,
                  "pr": 32,
                  "pt": 32,
                  "radius": 16
                },
                {
                  "bg": "#ffffff",
                  "pb": 32,
                  "pl": 32,
                  "pr": 32,
                  "pt": 32,
                  "radius": 16
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "colStyles": [
          {
            "bg": "transparent",
            "pb": 20,
            "pl": 20,
            "pr": 20,
            "pt": 20,
            "align": "center",
            "radius": 0,
            "shadow": "none",
            "marginY": 5,
            "paddingX": 20,
            "paddingY": 20,
            "fullWidth": "fluid",
            "borderColor": "var(--abc-color-border)",
            "borderStyle": "none",
            "borderWidth": 1
          }
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-steps-navy",
    "name": "Process steps — navy",
    "category": "Content",
    "icon": "🛤️",
    "blurb": "\"How we get you moving\" 3-step band (Stitch design).",
    "sections": [
      {
        "type": "row",
        "_name": "How We Get You Moving",
        "_style": {
          "bg": "#ffffff",
          "pb": 40,
          "pl": 40,
          "pr": 40,
          "pt": 40,
          "align": "center",
          "radius": 0,
          "shadow": "none",
          "marginY": 5,
          "paddingX": 20,
          "paddingY": 20,
          "fullWidth": "fluid",
          "borderColor": "var(--abc-color-border)",
          "borderStyle": "none",
          "borderWidth": 1
        },
        "columns": 1,
        "children": [
          [
            {
              "text": "How We Get You Moving",
              "type": "heading",
              "align": "center",
              "color": "#001e40",
              "level": "h2",
              "fontSize": 32
            },
            {
              "text": "A streamlined three-step process designed for the digital age.",
              "type": "text",
              "align": "center",
              "color": "#43474f",
              "fontSize": 16
            },
            {
              "gap": 16,
              "type": "row",
              "_name": "Cards",
              "columns": 3,
              "children": [
                [
                  {
                    "text": "Apply Online",
                    "type": "heading",
                    "align": "center",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 24
                  },
                  {
                    "text": "Complete a secure 10-minute application from your phone or computer.",
                    "type": "text",
                    "align": "center",
                    "color": "#43474f",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Get Approved",
                    "type": "heading",
                    "align": "center",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 24
                  },
                  {
                    "text": "I shop 30+ lenders to find your perfect match and secure your commitment.",
                    "type": "text",
                    "align": "center",
                    "color": "#43474f",
                    "fontSize": 16
                  }
                ],
                [
                  {
                    "text": "Close the Deal",
                    "type": "heading",
                    "align": "center",
                    "color": "#001e40",
                    "level": "h3",
                    "fontSize": 24
                  },
                  {
                    "text": "Finalize your paperwork and celebrate your new home or lower rate.",
                    "type": "text",
                    "align": "center",
                    "color": "#43474f",
                    "fontSize": 16
                  }
                ]
              ],
              "colStyles": [
                {
                  "bg": "#ffffff",
                  "align": "center"
                },
                {
                  "bg": "#ffffff",
                  "align": "center"
                },
                {
                  "bg": "#ffffff",
                  "align": "center"
                }
              ],
              "contentWidth": "boxed"
            }
          ]
        ],
        "contentWidth": "boxed"
      }
    ]
  },
  {
    "id": "hv-mortgage-hero",
    "name": "Local-expert hero",
    "category": "Hero",
    "icon": "🏠",
    "blurb": "Stitch-designed hero with photo + trust copy.",
    "sections": [
      {
        "gap": 16,
        "type": "row",
        "_name": "Cards",
        "_style": {
          "bg": "transparent",
          "mb": 5,
          "ml": 5,
          "mr": 5,
          "mt": 5,
          "pb": 40,
          "pl": 40,
          "pr": 40,
          "pt": 40,
          "align": "center",
          "radius": 0,
          "shadow": "none",
          "marginY": 5,
          "paddingX": 20,
          "paddingY": 20,
          "fullWidth": "fluid",
          "borderColor": "var(--abc-color-border)",
          "borderStyle": "none",
          "borderWidth": 1
        },
        "widths": [
          0.5880177514792899,
          0.4119822485207101
        ],
        "columns": 2,
        "children": [
          [
            {
              "text": "Ottawa's Trusted Mortgage Expert",
              "type": "heading",
              "color": "#1f477b",
              "level": "h3",
              "fontSize": 14
            },
            {
              "text": "Ottawa mortgages made simple.",
              "type": "heading",
              "color": "#001e40",
              "level": "h1",
              "fontSize": 48
            },
            {
              "text": "Navigate the complex world of home financing with confidence. I help Ottawa families secure the best rates and terms tailored to their unique financial goals.",
              "type": "text",
              "color": "#43474f",
              "fontSize": 18
            },
            {
              "gap": 12,
              "type": "row",
              "_name": "Buttons",
              "columns": 2,
              "children": [
                [
                  {
                    "href": "https://stitch.googleapis.com/#",
                    "type": "button",
                    "label": "Get Pre-Approved",
                    "radius": 12,
                    "bgColor": "#feae2c",
                    "variant": "solid",
                    "textColor": "#6b4500"
                  }
                ],
                [
                  {
                    "href": "https://stitch.googleapis.com/#",
                    "type": "button",
                    "label": "Book a Call",
                    "radius": 12,
                    "variant": "outline",
                    "textColor": "#001e40"
                  }
                ]
              ],
              "contentWidth": "boxed"
            }
          ],
          [
            {
              "url": "https://media.aibizconnect.app/00000000-0000-0000-0000-000000000000/uploads/imported/ceb48e6f30ba4de00fb39bf6d99390d2.png",
              "type": "image",
              "rounding": 16
            }
          ]
        ],
        "colStyles": [
          {},
          {}
        ],
        "contentWidth": "boxed"
      }
    ]
  }
] as unknown as PrebuiltTemplate[];
