import type { FeatureData } from "@/components/marketing/abc/FeaturePage";

/**
 * Product/feature pages. CRM is the Claude Design exemplar (design-handoffs/crm/); the rest reuse
 * its shape (FeaturePage) with feature-specific copy. Keyed by URL slug.
 */
export const FEATURES: Record<string, FeatureData> = {
  crm: {
    eyebrow: "CRM & Pipelines", h1: "A CRM that moves deals forward for you",
    sub: "Every contact, deal, and follow-up in one place — with pipelines that update themselves and AI that tells you who to call next.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Everything in one record", gridTitle: "Built to close, not just to store",
    features: [
      { icon: "👤", title: "Unified contacts", body: "One rich record per person — every email, call, note, and deal on a single timeline." },
      { icon: "🔀", title: "Pipelines that move themselves", body: "Deals advance stages automatically when a form is filled, a call is logged, or a doc is signed." },
      { icon: "✅", title: "Tasks & reminders", body: "Auto-created follow-ups so no lead waits — your day, sequenced for you." },
      { icon: "🎯", title: "AI lead scoring", body: "Every lead ranked by intent so you always know who to call next." },
      { icon: "🧩", title: "Smart segments", body: "Filter and group contacts in a click, then launch a campaign to the exact list." },
    ],
    demoEyebrow: "See it in action", demoTitle: "Your whole pipeline, at a glance",
    demoSub: "Drag deals between stages or let automations do it. Switch to contacts to see the full history — every email, call, and note in one timeline.",
    demoChecks: ["Stages advance on real activity", "AI flags the deals going cold", "One timeline per contact"], mockKind: "kanban",
    stats: [{ n: "8+ hrs", l: "saved every week on busywork" }, { n: "+32%", l: "more deals reach close" }, { n: "2 min", l: "to import your contacts" }],
    cta: { heading: "Put your pipeline on autopilot", sub: "Start free and import your contacts in minutes. Your AI takes it from there." },
  },
  "ai-builder": {
    eyebrow: "AI Builder", h1: "Describe it. Watch AI build it.",
    sub: "Tell AIBizConnect what you need — a page, an email, a funnel, an automation — and it builds it on-brand in seconds, ready to publish.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Build by describing", gridTitle: "Your whole platform, generated",
    features: [
      { icon: "🪄", title: "Pages & sites", body: "Describe a page and AI builds it on-brand — then edit it in plain language." },
      { icon: "✉️", title: "Emails & SMS", body: "Generate campaigns and follow-up sequences that sound like you." },
      { icon: "⚙️", title: "Automations", body: "Spin up triggers, waits, and branches from a single sentence." },
      { icon: "🎨", title: "On-brand by default", body: "Your colors, fonts, and voice applied to everything it makes." },
      { icon: "🔁", title: "Edit by asking", body: "\"Make it shorter, add a CTA\" — it updates instantly, no dragging." },
    ],
    demoEyebrow: "See it in action", demoTitle: "From prompt to published in minutes",
    demoSub: "Describe what you want and AI assembles the page, copy, and layout — review, tweak in plain language, and publish when it's perfect.",
    demoChecks: ["On-brand from the first draft", "Edit by asking, no dragging", "Publish the same day"], mockKind: "panel",
    stats: [{ n: "10×", l: "faster to a first draft" }, { n: "0", l: "code required" }, { n: "1 day", l: "to publish" }],
    cta: { heading: "Build it by describing it", sub: "Start free and let AI assemble your site, emails, and automations." },
  },
  "websites-funnels": {
    eyebrow: "Websites & Funnels", h1: "Sites and funnels that convert",
    sub: "AI-built, on-brand websites and high-converting funnels — forms, checkout, and follow-up wired straight into your CRM.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Built to convert", gridTitle: "From first click to closed deal",
    features: [
      { icon: "🌐", title: "AI website builder", body: "On-brand sites and landing pages that publish in one click." },
      { icon: "🧭", title: "Conversion funnels", body: "Multi-step funnels that guide visitors to book or buy." },
      { icon: "📝", title: "Forms & surveys", body: "Capture leads with smart forms wired straight to your CRM." },
      { icon: "💳", title: "Checkout & payments", body: "Sell products and services with built-in checkout." },
      { icon: "🔁", title: "Auto follow-up", body: "Every submission triggers the right sequence automatically." },
    ],
    demoEyebrow: "See it in action", demoTitle: "A funnel wired to your pipeline",
    demoSub: "Every form and checkout drops the lead into your CRM, tagged and routed — then the follow-up runs itself.",
    demoChecks: ["Forms feed the CRM instantly", "Checkout and booking built in", "Follow-up on autopilot"], mockKind: "panel",
    stats: [{ n: "1-click", l: "publish" }, { n: "+28%", l: "form conversion" }, { n: "0", l: "plugins to wire" }],
    cta: { heading: "Launch a site that sells", sub: "Start free and publish an on-brand site and funnel today." },
  },
  automations: {
    eyebrow: "Automations", h1: "Set it once. It runs forever.",
    sub: "Email and SMS sequences with triggers, waits, and branches that nurture, remind, and follow up — no code, no zaps.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Run the busywork for you", gridTitle: "Workflows that work while you sleep",
    features: [
      { icon: "⚡", title: "Triggers", body: "Start a flow on any lead action or stage change." },
      { icon: "⏱️", title: "Waits & delays", body: "Time messages perfectly without lifting a finger." },
      { icon: "🔀", title: "Branches", body: "Send different paths based on what each lead does." },
      { icon: "✉️", title: "Email + SMS", body: "Both channels in the same flow, in your voice." },
      { icon: "🔁", title: "Recover lost time", body: "Get back 8+ hours a week on follow-ups." },
    ],
    demoEyebrow: "See it in action", demoTitle: "A nurture flow, on autopilot",
    demoSub: "New lead in, welcome email, a wait, an SMS check-in, then the booked call — built once, running forever.",
    demoChecks: ["Trigger on any action", "Email and SMS together", "No code, no zaps"], mockKind: "panel",
    stats: [{ n: "8+ hrs", l: "saved per week" }, { n: "24/7", l: "follow-up" }, { n: "0", l: "code" }],
    cta: { heading: "Automate your follow-up", sub: "Start free and let sequences nurture every lead for you." },
  },
  "consumer-portal": {
    eyebrow: "Consumer Portal", h1: "A branded home for your clients",
    sub: "Give clients a branded portal for bookings, documents, payments, and messages — all under your name and domain.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Everything clients need", gridTitle: "Self-serve, on your brand",
    features: [
      { icon: "📅", title: "Bookings", body: "Clients self-schedule against your real availability." },
      { icon: "📄", title: "Documents", body: "Share, request, and e-sign files securely." },
      { icon: "💳", title: "Payments", body: "Invoices and payments, right in the portal." },
      { icon: "💬", title: "Messages", body: "A single thread per client, synced to your inbox." },
      { icon: "🏷️", title: "White-label", body: "Your brand and domain, not ours." },
    ],
    demoEyebrow: "See it in action", demoTitle: "One portal, every interaction",
    demoSub: "Bookings, docs, payments, and messages in one branded place — less back-and-forth, happier clients.",
    demoChecks: ["Self-serve bookings & docs", "Pay and sign in one place", "Fully white-labeled"], mockKind: "panel",
    stats: [{ n: "24/7", l: "self-serve access" }, { n: "100%", l: "white-label" }, { n: "1 day", l: "to launch" }],
    cta: { heading: "Give clients a better experience", sub: "Start free and launch a branded client portal today." },
  },
  marketplace: {
    eyebrow: "Marketplace", h1: "Extend your OS in a click",
    sub: "Apps, integrations, and add-ons that plug into AIBizConnect — connect the tools you love or add new powers without leaving your platform.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "More power, one click", gridTitle: "Apps & integrations that just work",
    features: [
      { icon: "🔌", title: "Integrations", body: "Connect email, calendar, payments, and more." },
      { icon: "🧩", title: "Add-ons", body: "Bolt on extra capabilities as you grow." },
      { icon: "🤝", title: "Partner apps", body: "Vetted tools built for AIBizConnect." },
      { icon: "⚙️", title: "One-click install", body: "Enable and configure without code." },
      { icon: "🔒", title: "Secure by default", body: "Scoped permissions and audit logs on every install." },
    ],
    demoEyebrow: "See it in action", demoTitle: "Your stack, in one place",
    demoSub: "Browse, install, and manage everything from inside your OS — no copy-pasting API keys across tabs.",
    demoChecks: ["One-click install", "Scoped, secure access", "Managed from your OS"], mockKind: "panel",
    stats: [{ n: "1-click", l: "install" }, { n: "50+", l: "integrations" }, { n: "0", l: "code" }],
    cta: { heading: "Add the powers you need", sub: "Start free and extend your platform from the marketplace." },
  },
  templates: {
    eyebrow: "Templates", h1: "Start from a head start",
    sub: "Industry-ready websites, funnels, and automation templates — pick one, apply your brand, and launch the same day.",
    trust: "14-day free trial · no credit card required",
    gridEyebrow: "Don't start from zero", gridTitle: "Proven templates for every business",
    features: [
      { icon: "🌐", title: "Website templates", body: "Conversion-ready sites tuned per industry." },
      { icon: "🧭", title: "Funnel templates", body: "Lead, booking, and sales funnels ready to launch." },
      { icon: "✉️", title: "Sequence templates", body: "Email & SMS nurtures ready to send." },
      { icon: "🎨", title: "Brandable in a click", body: "Apply your colors and fonts instantly." },
      { icon: "🏷️", title: "Industry-tuned", body: "Copy and structure written for your field." },
    ],
    demoEyebrow: "See it in action", demoTitle: "Apply your brand, publish today",
    demoSub: "Pick a template, apply your brand tokens, tweak the copy, and go live — no blank page, ever.",
    demoChecks: ["Industry-ready out of the box", "One-click brand apply", "Live the same day"], mockKind: "panel",
    stats: [{ n: "50+", l: "templates" }, { n: "1-click", l: "brand apply" }, { n: "1 day", l: "to live" }],
    cta: { heading: "Launch from a template", sub: "Start free and pick a head start for your industry." },
  },
};
