import type { IndustryData } from "@/components/marketing/abc/IndustryPage";

/**
 * Per-industry solution pages. Real Estate is the Claude Design exemplar
 * (design-handoffs/realestate/); the other verticals reuse its shape (IndustryPage) with
 * vertical-specific copy. Keyed by URL slug for app/solutions/[industry].
 */
export const INDUSTRIES: Record<string, IndustryData> = {
  "real-estate": {
    eyebrow: "For Real Estate",
    h1: "Every lead worked. Every showing booked. On autopilot.",
    sub: "AIBizConnect OS gives agents and brokers an IDX-ready site, a CRM that captures every buyer and seller, and an AI concierge that books showings while you're out on tour.",
    secondaryCta: { label: "See it for agents", href: "#features" },
    trust: "14-day free trial · no credit card · MLS & IDX ready",
    heroCard: { badge: "New listing", title: "412 Eastside Ave", meta: "$615,000", sub: "3 bd · 2 ba · 1,840 sqft · Austin, TX", actions: ["Book a showing", "Request info"], chips: [{ i: "JT", name: "Jordan Tate · Buyer", note: "Booked a tour · Fri 10:00 AM", tag: "Booked" }, { i: "SP", name: "Sam Price · Seller lead", note: "AI sent valuation · nurturing", tag: "Nurturing" }] },
    stats: [{ n: "38%", l: "more leads captured" }, { n: "12 hrs", l: "saved per week" }, { n: "24/7", l: "showing booking" }, { n: "1 day", l: "to go live" }],
    featuresEyebrow: "Built for how agents work", featuresTitle: "Your listings, leads, and showings — in one place", featuresSub: "Everything a real estate business needs to capture, convert, and close — no plugins to wire up.",
    features: [
      { title: "IDX-ready listings site", bullets: ["MLS & IDX feed built in", "SEO-ready property pages"] },
      { title: "Buyer & seller lead capture", bullets: ["Instant home-valuation funnel", "Auto-tagged buyer vs. seller"] },
      { title: "Showing & tour bookings", bullets: ["Calendar-synced scheduling", "Auto reminders cut no-shows"] },
      { title: "Listing & sphere nurture", bullets: ["New-listing alerts on autopilot", "Past-client check-in sequences"] },
    ],
    conciergeEyebrow: "AI concierge for agents", conciergeTitle: "It answers inquiries the second they land", conciergeSub: "While you're showing a home, your concierge greets new buyers and sellers, qualifies them, and drops a booked showing straight on your calendar.",
    conciergeChecks: ["Replies to every inquiry in seconds, day or night", "Qualifies buyers and sellers before they reach you", "Books tours straight into your calendar"],
    concierge: { name: "Listing Concierge", sub: "412 Eastside Ave", status: "Online", msgs: [{ from: "bot", t: "Hi! Interested in 412 Eastside Ave? I can book you a private showing this week. 🏡" }, { from: "user", t: "Yes — does Friday work?" }, { from: "bot", t: "Friday 10:00 AM is open. You're booked — added to Marcus's calendar and saved in the CRM. ✅" }], confirm: "Showing booked · added to CRM" },
    stepsTitle: "From sign-up to first booked showing",
    steps: [{ n: "1", title: "Connect your market", body: "Add your MLS/IDX and brand — AI builds your listings site and CRM in minutes." }, { n: "2", title: "AI works your leads", body: "Every buyer and seller is captured, qualified, and nurtured automatically." }, { n: "3", title: "Show up to booked tours", body: "Walk into a full calendar while follow-ups run themselves in the background." }],
    testimonial: { quote: "I replaced my website, CRM, and email tool with AIBizConnect — and my AI books showings while I sleep. I closed three extra deals last quarter just from leads it caught at night.", initials: "MR", name: "Marcus Reyes", role: "Realtor · Austin, TX" },
    cta: { heading: "Build your real estate business on AIBizConnect OS", sub: "Launch an IDX-ready site and let your AI work every lead. Live the same day." },
  },

  mortgage: {
    eyebrow: "For Mortgage",
    h1: "Turn rate-shoppers into funded loans.",
    sub: "AIBizConnect OS gives loan officers application funnels, a CRM that tracks every borrower, and an AI concierge that pre-qualifies and follows up through every milestone.",
    secondaryCta: { label: "See it for loan officers", href: "#features" },
    trust: "14-day free trial · no credit card · built for LOs",
    heroCard: { badge: "New application", title: "Conventional 30-yr", meta: "$420,000", sub: "Pre-qual · 740 FICO · Austin, TX", actions: ["Start application", "Get pre-qualified"], chips: [{ i: "AM", name: "Ava Morgan · Borrower", note: "Pre-qual sent · nurturing", tag: "Nurturing" }, { i: "RD", name: "Ray Diaz · Refi lead", note: "Booked a call · Thu 2:00 PM", tag: "Booked" }] },
    stats: [{ n: "32%", l: "more apps started" }, { n: "10 hrs", l: "saved per week" }, { n: "24/7", l: "pre-qualification" }, { n: "1 day", l: "to go live" }],
    featuresEyebrow: "Built for how LOs work", featuresTitle: "Applications, pipeline, and follow-ups — in one place", featuresSub: "Everything a mortgage business needs to capture, qualify, and fund — no plugins to wire up.",
    features: [
      { title: "Application funnels", bullets: ["Branded 1003-ready intake", "Auto-tagged purchase vs. refi"] },
      { title: "Pre-qualification flows", bullets: ["Instant pre-qual questionnaire", "Soft-pull-ready handoff"] },
      { title: "Milestone follow-ups", bullets: ["Status updates on autopilot", "Rate-watch & check-in sequences"] },
      { title: "Pipeline & referrals", bullets: ["Realtor-partner co-marketing", "Past-client refi alerts"] },
    ],
    conciergeEyebrow: "AI concierge for LOs", conciergeTitle: "It pre-qualifies the moment they apply", conciergeSub: "While you're closing a file, your concierge greets new borrowers, runs the pre-qual questions, and books the call straight on your calendar.",
    conciergeChecks: ["Replies to every inquiry in seconds", "Pre-qualifies borrowers before they reach you", "Books calls straight into your calendar"],
    concierge: { name: "Loan Concierge", sub: "Conventional 30-yr", status: "Qualifying", msgs: [{ from: "bot", t: "Hi! Shopping a rate? I can pre-qualify you in 2 minutes and book a call." }, { from: "user", t: "Yes — purchase, around $420k." }, { from: "bot", t: "Great — you look pre-qualified. Thursday 2pm is open; I've booked it and saved you in the CRM. ✅" }], confirm: "Borrower pre-qualified · call booked" },
    stepsTitle: "From sign-up to your first funded lead",
    steps: [{ n: "1", title: "Connect your products", body: "Add your loan products and brand — AI builds your funnels and CRM." }, { n: "2", title: "AI works your borrowers", body: "Every applicant is captured, pre-qualified, and nurtured automatically." }, { n: "3", title: "Fund more loans", body: "Walk into booked calls while milestone follow-ups run themselves." }],
    testimonial: { quote: "The concierge pre-qualifies rate-shoppers overnight and books my calls. I funded two extra loans last month from leads I'd have missed.", initials: "DW", name: "Dana Whitfield", role: "Loan Officer · Tampa" },
    cta: { heading: "Build your mortgage business on AIBizConnect OS", sub: "Launch application funnels and let your AI qualify every borrower. Live the same day." },
  },

  insurance: {
    eyebrow: "For Insurance",
    h1: "Quote faster. Win every renewal.",
    sub: "AIBizConnect OS gives agents quote-intake funnels, a CRM that tracks every policy, and an AI concierge that answers, quotes, and keeps policyholders close.",
    secondaryCta: { label: "See it for agents", href: "#features" },
    trust: "14-day free trial · no credit card · P&C and life ready",
    heroCard: { badge: "New quote", title: "Auto + Home bundle", meta: "$1,840/yr", sub: "Multi-policy · Austin, TX", actions: ["Get a quote", "Request callback"], chips: [{ i: "SL", name: "Sofia Lin · New quote", note: "AI sent options · nurturing", tag: "Nurturing" }, { i: "TP", name: "Theo Park · Renewal", note: "Booked review · Fri 10:00 AM", tag: "Booked" }] },
    stats: [{ n: "30%", l: "more quotes started" }, { n: "9 hrs", l: "saved per week" }, { n: "24/7", l: "quote intake" }, { n: "1 day", l: "to go live" }],
    featuresEyebrow: "Built for how agents work", featuresTitle: "Quotes, renewals, and policies — in one place", featuresSub: "Everything an insurance business needs to quote, bind, and retain — no plugins to wire up.",
    features: [
      { title: "Quote-intake funnels", bullets: ["Branded multi-line intake", "Auto-tagged by policy type"] },
      { title: "Renewal automation", bullets: ["Renewal reminders on autopilot", "Win-back sequences for lapses"] },
      { title: "Policyholder nurture", bullets: ["Cross-sell & bundle prompts", "Annual review scheduling"] },
      { title: "Pipeline & referrals", bullets: ["Referral request sequences", "Household & business rollups"] },
    ],
    conciergeEyebrow: "AI concierge for agents", conciergeTitle: "It quotes the second they ask", conciergeSub: "While you're with a client, your concierge greets new prospects, gathers quote details, and books the review straight on your calendar.",
    conciergeChecks: ["Replies to every inquiry in seconds", "Gathers quote details before they reach you", "Books reviews straight into your calendar"],
    concierge: { name: "Quote Concierge", sub: "Auto + Home", status: "Quoting", msgs: [{ from: "bot", t: "Hi! Looking for a quote on a renewal? I can pull options in 2 minutes." }, { from: "user", t: "Yes — auto + home bundle." }, { from: "bot", t: "Perfect. Friday 10am works for a 15-min review — I've booked it and saved you in the CRM. ✅" }], confirm: "Lead captured · review booked" },
    stepsTitle: "From sign-up to your first bound policy",
    steps: [{ n: "1", title: "Connect your lines", body: "Add your products and brand — AI builds your quote funnels and CRM." }, { n: "2", title: "AI works your quotes", body: "Every prospect is captured, quoted, and nurtured automatically." }, { n: "3", title: "Win more renewals", body: "Walk into booked reviews while renewal follow-ups run themselves." }],
    testimonial: { quote: "Setup took an afternoon. The concierge qualifies leads better than the VA I was paying $2k a month for.", initials: "DW", name: "Dana Whitfield", role: "Insurance Agent · Tampa" },
    cta: { heading: "Build your insurance business on AIBizConnect OS", sub: "Launch quote funnels and let your AI win every renewal. Live the same day." },
  },

  legal: {
    eyebrow: "For Legal",
    h1: "Intake every matter. Chase no one.",
    sub: "AIBizConnect OS gives firms client-intake funnels, a CRM that tracks every matter, and an AI concierge that screens, books consults, and follows up on retainers.",
    secondaryCta: { label: "See it for firms", href: "#features" },
    trust: "14-day free trial · no credit card · intake & conflicts ready",
    heroCard: { badge: "New intake", title: "Family law · consult", meta: "Retainer pending", sub: "Conflict check passed · Austin, TX", actions: ["Book a consult", "Request callback"], chips: [{ i: "DR", name: "Dana Ruiz · Intake", note: "Conflict check passed · nurturing", tag: "Nurturing" }, { i: "MK", name: "Marcus Kane · Consult", note: "Booked · Thu 2:00 PM", tag: "Booked" }] },
    stats: [{ n: "35%", l: "more consults booked" }, { n: "11 hrs", l: "saved per week" }, { n: "24/7", l: "client intake" }, { n: "1 day", l: "to go live" }],
    featuresEyebrow: "Built for how firms work", featuresTitle: "Intake, consults, and matters — in one place", featuresSub: "Everything a firm needs to screen, sign, and serve — no plugins to wire up.",
    features: [
      { title: "Client-intake funnels", bullets: ["Branded matter intake forms", "Auto-tagged by practice area"] },
      { title: "Consult booking", bullets: ["Calendar-synced scheduling", "Auto reminders cut no-shows"] },
      { title: "Retainer follow-ups", bullets: ["Engagement-letter sequences", "Unpaid-retainer reminders"] },
      { title: "Conflict & matters", bullets: ["Conflict-check capture", "Matter status nurture"] },
    ],
    conciergeEyebrow: "AI concierge for firms", conciergeTitle: "It screens intakes the second they land", conciergeSub: "While you're in court, your concierge greets new clients, screens the matter, and books the consult straight on your calendar.",
    conciergeChecks: ["Replies to every inquiry in seconds", "Screens matters before they reach you", "Books consults straight into your calendar"],
    concierge: { name: "Intake Concierge", sub: "Family law", status: "Screening", msgs: [{ from: "bot", t: "Hi! I can start your intake and book a consult. What's the matter about?" }, { from: "user", t: "Family law — a custody question." }, { from: "bot", t: "Thanks — conflict check is clear. Thursday 2pm is open; I've booked it and saved your intake. ✅" }], confirm: "Intake captured · consult booked" },
    stepsTitle: "From sign-up to your first booked consult",
    steps: [{ n: "1", title: "Connect your practice", body: "Add your practice areas and brand — AI builds your intake and CRM." }, { n: "2", title: "AI works your intakes", body: "Every matter is captured, screened, and nurtured automatically." }, { n: "3", title: "Sign more clients", body: "Walk into booked consults while retainer follow-ups run themselves." }],
    testimonial: { quote: "Intake used to leak after hours. Now every matter is screened and booked by morning — we sign more clients with less chasing.", initials: "PA", name: "Priya Anand", role: "Managing Partner" },
    cta: { heading: "Build your firm on AIBizConnect OS", sub: "Launch intake funnels and let your AI screen every matter. Live the same day." },
  },

  coaching: {
    eyebrow: "For Coaching",
    h1: "Fill your calendar with discovery calls.",
    sub: "AIBizConnect OS gives coaches booking funnels, a CRM that tracks every client, and an AI concierge that books discovery calls and keeps clients engaged between sessions.",
    secondaryCta: { label: "See it for coaches", href: "#features" },
    trust: "14-day free trial · no credit card · programs & booking ready",
    heroCard: { badge: "New booking", title: "Discovery call · 30 min", meta: "Program: 1:1 Coaching", sub: "Goal: scale to six figures · Austin, TX", actions: ["Book a call", "Join program"], chips: [{ i: "AM", name: "Ava Morgan · Lead", note: "AI sent intake · nurturing", tag: "Nurturing" }, { i: "RD", name: "Ray Diaz · Client", note: "Session booked · Fri 10:00 AM", tag: "Booked" }] },
    stats: [{ n: "40%", l: "more calls booked" }, { n: "10 hrs", l: "saved per week" }, { n: "24/7", l: "discovery booking" }, { n: "1 day", l: "to go live" }],
    featuresEyebrow: "Built for how coaches work", featuresTitle: "Bookings, programs, and clients — in one place", featuresSub: "Everything a coaching business needs to book, deliver, and retain — no plugins to wire up.",
    features: [
      { title: "Booking funnels", bullets: ["Branded discovery-call funnel", "Auto-tagged by program"] },
      { title: "Program delivery", bullets: ["Sessions, modules, and check-ins", "Client portal for materials"] },
      { title: "Client nurture", bullets: ["Between-session accountability", "Renewal & upsell sequences"] },
      { title: "Pipeline & referrals", bullets: ["Testimonial request sequences", "Referral & waitlist capture"] },
    ],
    conciergeEyebrow: "AI concierge for coaches", conciergeTitle: "It books discovery calls while you coach", conciergeSub: "While you're in a session, your concierge greets new leads, qualifies the fit, and books the discovery call straight on your calendar.",
    conciergeChecks: ["Replies to every inquiry in seconds", "Qualifies fit before they reach you", "Books calls straight into your calendar"],
    concierge: { name: "Coaching Concierge", sub: "1:1 Coaching", status: "Qualifying", msgs: [{ from: "bot", t: "Hi! Curious about coaching? I can find your fit and book a free discovery call." }, { from: "user", t: "Yes — I want to scale my business." }, { from: "bot", t: "Love it. Friday 10am is open; you're booked and I've saved your intake. ✅" }], confirm: "Lead qualified · call booked" },
    stepsTitle: "From sign-up to a full calendar",
    steps: [{ n: "1", title: "Connect your programs", body: "Add your offers and brand — AI builds your booking funnels and CRM." }, { n: "2", title: "AI works your leads", body: "Every lead is captured, qualified, and nurtured automatically." }, { n: "3", title: "Coach more clients", body: "Walk into booked calls while accountability follow-ups run themselves." }],
    testimonial: { quote: "The assistant follows up with every lead overnight. My calendar fills itself now — I just show up and coach.", initials: "PA", name: "Priya Anand", role: "Business Coach" },
    cta: { heading: "Build your coaching business on AIBizConnect OS", sub: "Launch booking funnels and let your AI fill your calendar. Live the same day." },
  },

  agencies: {
    eyebrow: "For Agencies",
    h1: "Run every client brand from one login.",
    sub: "AIBizConnect OS gives agencies white-label sub-accounts, a CRM per client, and an AI concierge in every brand — so you scale from solo to a full agency without adding tools.",
    secondaryCta: { label: "See it for agencies", href: "#features" },
    trust: "14-day free trial · no credit card · white-label ready",
    heroCard: { badge: "Client sub-account", title: "Northbeam Agency", meta: "6 client brands", sub: "White-label · per-seat roles", actions: ["Open client", "Add brand"], chips: [{ i: "ER", name: "Eastside Realty", note: "Site live · 42 leads this week", tag: "Live" }, { i: "HA", name: "Hale Advisory", note: "Onboarding · setup 80%", tag: "Setup" }] },
    stats: [{ n: "6", l: "client brands per login" }, { n: "12 hrs", l: "saved per week" }, { n: "100%", l: "white-label" }, { n: "1 day", l: "to onboard a client" }],
    featuresEyebrow: "Built for how agencies work", featuresTitle: "Clients, brands, and reporting — in one place", featuresSub: "Everything an agency needs to launch, manage, and scale client brands — no plugins to wire up.",
    features: [
      { title: "White-label sub-accounts", bullets: ["Your brand and domain, not ours", "Per-client CRM and pipelines"] },
      { title: "Multi-brand management", bullets: ["One login across every client", "Templates cloned in seconds"] },
      { title: "Team roles & seats", bullets: ["Granular roles and permissions", "Assign work per client"] },
      { title: "Reporting & billing", bullets: ["Roll-up reporting across clients", "Per-seat entitlements & billing"] },
    ],
    conciergeEyebrow: "AI concierge for agencies", conciergeTitle: "An AI concierge in every client brand", conciergeSub: "Each client gets their own concierge that answers, qualifies, and books — in their voice — while you manage everything from one place.",
    conciergeChecks: ["A branded concierge per sub-account", "Qualifies and books for every client", "Roll-up reporting across all brands"],
    concierge: { name: "Agency Concierge", sub: "Northbeam · 6 brands", status: "Online", msgs: [{ from: "bot", t: "New lead for Eastside Realty — qualified and routed to their pipeline." }, { from: "user", t: "Great — book the showing." }, { from: "bot", t: "Done. Booked Friday 10am in Eastside's calendar and logged it in their CRM. ✅" }], confirm: "Lead routed · booked in client brand" },
    stepsTitle: "From sign-up to your first client brand",
    steps: [{ n: "1", title: "Spin up a brand", body: "Create a white-label sub-account with the client's brand and domain." }, { n: "2", title: "AI works their leads", body: "Each client's leads are captured, qualified, and nurtured automatically." }, { n: "3", title: "Scale your book", body: "Add brands in minutes and report across all of them from one login." }],
    testimonial: { quote: "We run six client brands from one login. White-label sub-accounts are a game changer for our agency.", initials: "PA", name: "Priya Anand", role: "Founder · Northbeam Agency" },
    cta: { heading: "Build your agency on AIBizConnect OS", sub: "Launch white-label client brands and let AI work every one. Live the same day." },
  },
};

export const INDUSTRY_SLUGS = Object.keys(INDUSTRIES);
